### ISSUE TITLE
This hazard in Egg Corridor don't work as intended

### ISSUE THREAD

**Issue by ViperAcidZX** [doukutsu-rs/doukutsu-rs#100]
For some reason this hazard does not hurt the player at all when normally it's supposed to do enough damage to install kill the player but it just phases through the player like nothing in this build of doukutsu-rs.

![doukutsu-rs x86_64-2022_03_22_23-26-46](https://user-images.githubusercontent.com/19318128/159618545-88a601ab-379a-49fa-80de-9ee38d5839d7.png)

**Comment by ViperAcidZX** [comment]
Never mind, this appears to be fixed in the latest nightly build from AppVeyer.

**Comment by alula** [comment]
I'm pretty sure you have accidentally hit the debug god mode key (F3)

**Comment by ViperAcidZX** [comment]
Yep that was one me since I didn't know that F3 would do that. Thank you for the heads up.
