### ISSUE TITLE
Alt menus appearing based on challenge time

### ISSUE THREAD

**Issue by abzium** [doukutsu-rs/doukutsu-rs#101]
Using Epic Games data files, after completing Machine Gun Challenge with a time of 2'00'07, the menu player sprite changed to Sue (and with Safety as it would if Hell was beaten under 3 minutes. I don't have a save file with Hell beaten in d-rs.
![image](https://user-images.githubusercontent.com/50076007/160212980-1087f178-a046-40ad-aa1f-82f721a1905f.png)

**Comment by dawndus** [comment]
I can't replicate this, can you show me what files you have in `%localappdata%\doukutsu-rs\data`? 

![doukutsu-rs x86_64_XrORL3mvFw](https://user-images.githubusercontent.com/96957561/160213733-93f27f62-810b-4a92-9855-5da11ce9406e.png)
![doukutsu-rs x86_64_HQHoXf5kW0](https://user-images.githubusercontent.com/96957561/160213739-36c1fe21-bb50-4579-96d2-b0874b169ae7.png)

**Comment by abzium** [comment]
![image](https://user-images.githubusercontent.com/50076007/160223110-9980a81d-0536-46a4-b585-c9eddce9792b.png)

**Comment by dawndus** [comment]
You had to have ran the challenge on an older version -- `ProfileEasyModmod.dat` can't be created now, saves with that kind of name were dropped [Feb 22nd](https://github.com/doukutsu-rs/doukutsu-rs/commit/5cf63660efcd6d1a58950ca47c7c0346510c59a7#diff-5299de7b2fd6d261cb56d5e5cbb5b524f0ee345e7e86075246de1de4a1033a30L559).
