### ISSUE TITLE
Boss Attack Challenge starts from Monster X

### ISSUE THREAD

**Issue by RancidJackalope** [doukutsu-rs/doukutsu-rs#117]
Cave Story + GOG version. Linux (Ubuntu 20.04 LTS).
Just start Boss Attack and it would spawn you at Monster X gate
![Boss-Attack](https://user-images.githubusercontent.com/101689912/163890973-f4987d5a-5ec6-4402-9ecb-3c19b516e5a6.png)
.

**Comment by Daedliy** [comment]
Are you sure you're using the releases from AppVeyor? Sounds like an ancient bug

**Comment by RancidJackalope** [comment]
I just built it myself with cargo as always (`cargo build --release`). It was working properly not so long ago for me.
I tried the releases you just linked and they behave the same way. If it's something wrong on my end, then I am clueless.

**Comment by RancidJackalope** [comment]
I modded some bitmaps but it was before I started using doukutsu-rs. It was working not so long ago. Maybe I messed with something else and I forgot, who knows. I'll see what I can do and I'll report back.

**Comment by RancidJackalope** [comment]
It was on my end. In my _"mods.txt"_ file I wrote _"/Boss/mod/"_ because that's how my folder is called, but it should be _"/boss/mod/"_ regardless. At least I didn't go the `git bisect` route for nothing; sorry I wasted a bug report and your time, though. Thank you very much for your work.

**Comment by Daedliy** [comment]
No worries! Next time try to take it to the discord server so we can sort out actual problems that need to be reported
