### ISSUE TITLE
Weapon-related inaccuracies

### ISSUE THREAD

**Issue by periwinkle9** [doukutsu-rs/doukutsu-rs#120]
- [x] When switching from the Spur to another weapon using the weapon swap keys, the Spur should reset to Level 1
- [x] The vanilla game has a fire rate limiter which appears to be unimplemented in d-rs: When pressing the fire button less than 4 frames after a previous shot, the weapons code is not ran on that frame, preventing the weapon from firing. For comparison: left is d-rs, right is freeware with a turbo mod:
![firerate](https://user-images.githubusercontent.com/11477985/164484829-73c1f7b8-54f4-46c4-9ae0-fc705e936d7d.png)
- [x] When boosting up against a ceiling and shooting Curly's Nemesis, her shot collides with the ceiling in freeware, but not in d-rs:
![nem](https://user-images.githubusercontent.com/11477985/164485580-772cfd4b-5193-43fc-b88d-1b2589ccab45.png)
- [x] When standing inside of Ballos and shooting upwards with your Nemesis + Curly's Nemesis, the two shots together deal 24 damage in vanilla but 28 damage in d-rs:
Freeware:
https://user-images.githubusercontent.com/11477985/164487845-0d500b87-775d-45c3-a55b-11cf77cb103f.mp4
d-rs:
https://user-images.githubusercontent.com/11477985/164487854-4fba962b-170d-433e-856b-1f7fa299aa3c.mp4
- [x] (From Discord) Enemy damage numbers should not display until after a period of not taking damage

**Comment by periwinkle9** [comment]
I just noticed that in the first image above, the Spur shots seem to have a longer range in d-rs compared to freeware? Can't tell if it's just because I'm standing more to the left in the d-rs screenshot, but the positioning looks pretty close to my eye.

**Comment by jozsefsallai** [comment]
All of these *should* be fixed, but feel free to reopen if any of them are still inaccurate.
