### ISSUE TITLE
Nemesis challenge bugs

### ISSUE THREAD

**Issue by Mawile0** [doukutsu-rs/doukutsu-rs#121]
- [x] the booster 2.0 isn't automatically equipped when you get it as it would be in vanilla CS+
- [x] the block spawning and de-spawning is different in some way than vanilla. it takes longer to happen and sometimes just breaks entirely in situations where it wouldn't in vanilla cs+ (video of the latter happening: https://youtu.be/mK2k_IlJZEY?t=280)
- [x] rogue night ghost projectiles spotted in the upper left corner of this screenshot: https://puu.sh/IW5UJ/cb681e4633.png

**Comment by dawndus** [comment]
Fixed in e4ec69b6dc491b21715b7d858ab6496ee5e60554
