### ISSUE TITLE
Better Controller Support (enhancement)

### ISSUE THREAD

**Issue by RedCoder09** [doukutsu-rs/doukutsu-rs#125]
I feel like it would be a good idea to add rumble support and shoulder button pressure adjustments, like nxengine-evo.

**Comment by jozsefsallai** [comment]
I feel like it would be a good idea to have controller support **at all**, which is something that's being worked on.

**Comment by dawndus** [comment]
Known and currently being addressed so I'm going to close this.

**Comment by RedCoder09** [comment]
I realize that the control support is being worked on, but, just out of curiosity, is the rumble support being worked on too?
