### ISSUE TITLE
some bugs in nightly build linux lastest one

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#127]
-machine gun challenge should be unlocked already
-machine gun challege this bat make water noize all along the room
![Screenshot 2022-04-22 222632](https://user-images.githubusercontent.com/101902085/165199444-dd927380-d9c3-40cd-9c57-75e26ab6fa9f.png)
- nemsis challenge is not unlocked after first save (must save second time)
- water way shortcut is not fixed yet
- last cave when critcher jump into red water 
blue drops appears instaid of red water drops(its blood not lava)
-blood sained sanctury 
booster bubble appears in top screen 
![Screenshot_2022-04-24-03-09-21-810_com mxtech videoplayer ad](https://user-images.githubusercontent.com/101902085/165200002-33a7e71a-ffad-47cf-ae92-a4f551865e00.jpg)

**Comment by dananothername** [comment]
dawndus do i need to change my name

**Comment by dawndus** [comment]
- Machine gun challenge requires item 35 on Switch, not that you'd know that since you have pirated data and haven't actually played it.
- Waterway shortcut is confirmed to work
