### ISSUE TITLE
spur & delete inaccuracy 

### ISSUE THREAD

**Issue by jwump** [doukutsu-rs/doukutsu-rs#131]
when the spur is charged to level 3 (but not max), you can boost up against a delete and shoot through it, which helps save time in speedruns of hell. the bug works in version 0.99.0.425 but was broken somewhere between that and version 0.99.0.427. this bug is replicable in official versions of the game 

https://user-images.githubusercontent.com/105085574/167225152-e764a5c7-a9cc-4712-bf75-d9d143a23922.mp4
version 0.99.0.455 (switch data)

https://user-images.githubusercontent.com/105085574/167225194-e0362781-898e-48bc-92c9-9a9e2d1aabe2.mp4
version 0.99.0.425 (switch data)

https://user-images.githubusercontent.com/105085574/167227639-ec4f2613-786f-4293-97f4-6bd39013b4dd.mp4
version 0.99.0.455 (steam cs+ data)

https://user-images.githubusercontent.com/105085574/167227435-c3280766-0427-4ea1-93b5-e1d9d9a5e38c.mp4
steam cs+

it is annoying to run through hell knowing i could have gotten a better time if i was playing on an older version of d-rs

**Comment by jwump** [comment]
** d-rs with steam cs+ data is running ver. 0.99.0,455

**Comment by dawndus** [comment]
The only recent change to the spur was in e4ec69b6dc491b21715b7d858ab6496ee5e60554, where the bullet spawn location was moved back to match vanilla, there might be something missing there.
