### ISSUE TITLE
booster bubble issue

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#136]
when boosting to the right the bubble come out of quote chest instead of his back 
![Screenshot_2022-05-12-13-43-14-503_io github doukutsu_rs](https://user-images.githubusercontent.com/101902085/168155546-0a1c5d5d-a532-4307-9b9f-6d80f94014c0.jpg)
also pls fix button position 
i can't speedrun android port
and recording doesn't work even after finishing the challenge 
it was working before deleting first record then it doesn't work forever

**Comment by jozsefsallai** [comment]
> also pls fix button position
> i can't speedrun android port

No one made doukutsu-rs for the sole purpose of you being able to speedrun the Android port. Also we are working on this project in our free time and out of passion. Quit demanding and be patient.

> and recording doesn't work even after finishing the challenge
> it was working before deleting first record then it doesn't work forever

Well, did you get a better time? If you delete a recording the game will not create a new recording until you beat your best time.
