### ISSUE TITLE
issues in muiltyplayer mode

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#143]
first of all I'd like to thank you guys for the update 
i always wanted to TAS cs muiltyplayer 
i am using this version 
![shot-2022-06-27_18-37-10](https://user-images.githubusercontent.com/101902085/176032275-e88a665b-984d-420d-91bb-23e8785f2b01.jpg)
the red water (water with mimga blood) in final cave still cause blue drops
the current here should be where quote is standing 
![shot-2022-06-27_18-39-04](https://user-images.githubusercontent.com/101902085/176032525-7c28a7c1-fc21-4926-b3a9-29b8edbec123.jpg)
the last issue is when playing muiltyplayer after given the booster to sue mother it will only take the first player's booster but it's fixed when restarting from  a save

**Comment by dananothername** [comment]
1-in challenges the second player doesn't have the booster plus where he die,  the first player can move but the weapon is not 

https://user-images.githubusercontent.com/101902085/176284099-5419bd91-cbbb-4588-8752-76fadfe34252.mp4


and  if the first players still moving and touched the spikes

https://user-images.githubusercontent.com/101902085/176284139-436cdfa6-764f-4eef-b870-5f6e0090fc16.mp4

this happen

**Comment by jozsefsallai** [comment]
> in challenges the second player doesn't have the booster

I wonder why... 🙄 

> and if the first players still moving and touched the spikes this happen

Literally the first bug in #107. Please read through that list before reporting coop bugs.

**Comment by dananothername** [comment]
thanks I'll wait for updates

**Comment by dananothername** [comment]
got another 
- last balrog: when balrog land on second quote 
the first quote teleport and merge with him 
the second quote become invisible but still take damage 
- monster x some time  follow the second quote  and  get out of his range 
- 
![Screenshot 2022-07-02 172301](https://user-images.githubusercontent.com/101902085/177087175-0740f188-6628-4f62-88a4-1fa94b8e8917.png)
the bolders move late for the second quote 
![Screenshot 2022-07-02 171304](https://user-images.githubusercontent.com/101902085/177087704-e363a09f-5352-42aa-a9ef-c39f511075ad.png)

https://user-images.githubusercontent.com/101902085/177087800-50075db8-bd52-460d-a0e4-280fa98b64c6.mp4

after defeating egor and changing the room the gate is open 
the second player doesn't have the right to open menu 
and those buttons
![Picsart_22-06-27_21-40-48-363](https://user-images.githubusercontent.com/101902085/177088129-645e445a-7805-4b8f-b76f-24255d2c23a9.png)
