### ISSUE TITLE
Snack block rendering error

### ISSUE THREAD

**Issue by Brayconn** [doukutsu-rs/doukutsu-rs#147]
When the snack block graphic from NpcSym is deleted, the underlying graphic from the tileset should show through.
(Left is d-rs, right is freeware)
![image](https://user-images.githubusercontent.com/29030756/179639864-666294bd-6fb8-4b8a-a222-8a91f3af42f1.png)

~~don't ask why the critters in freeware are showing up as Mahin~~

**Comment by jozsefsallai** [comment]
why do the critters in freeware show up as Mahin?
