### ISSUE TITLE
Can't continue the game in the last scene after defeating the doctor and mad-core

### ISSUE THREAD

**Issue by HaidarAhmad23** [doukutsu-rs/doukutsu-rs#148]
Please give the continue button or whatever so that the game can continue, so that we can get the v.2.0 booster, new polar star, and can beat the new cave story boss

**Comment by Daedliy** [comment]
You may be confused, the main goal of this engine _**isn't to change how Cave Story plays out**_, to achieve the Best Ending, you must create a new save as you would on both Freeware and CS+

**Comment by jozsefsallai** [comment]
If you're on Android, please wait a bit more for the next release, which adds multiple save profiles and save deletion. Also, if you're stuck at the end of the credits, you can just restart the game to get back to the main menu.

**Comment by dawndus** [comment]
Closing this, it's asking for changes to the base game itself.
