### ISSUE TITLE
Problems with controller remapping settings and some suggestions

### ISSUE THREAD

**Issue by ViperAcidZX** [doukutsu-rs/doukutsu-rs#150]
I was trying to remap my controls but when I tried to changing Shoot from B button to X on my Xbox controller, it screws up Jump on A button and it suddenly changes to X when I didn't want it to, and when I tried to change it back, it doesn't want to change unless I go back to the default controls. I was running into these problems with the latest AppVeyor build that just came out.

- [x] fix jump/shoot swap bug

Could it be possible to make the default face button configuration to this?

**Xbox, PlayStation, Nintendo**
A / ✕ / B - Jump/Confirm
B / 〇 / A - Cancel
X / □ / Y - Shoot
Y / △ / X - Inventory/Skip

- [x] update default gamepad controls

Also could it be possible to add the ability to rebind the menu controls? For example, if one is playing the with a Switch Pro Controller, they could change the Confirm button to A (East) or someone prefers to change it to B (South) on the same controller.

- [x] add menu ok/back as remappable controls

**Comment by alula** [comment]
@jozsefsallai https://github.com/gabomdq/SDL_GameControllerDB

**Comment by jozsefsallai** [comment]
> when I tried to changing Shoot from B button to X on my Xbox controller, it screws up Jump on A button and it suddenly changes to X when I didn't want it to

My latest commit was supposed to prevent a glitch where you can assign the same button to both shoot and jump, rendering the menu unusable (the idea is that if you try to do that, it should essentially swap the Jump and Shoot buttons). Guess something went wrong there, I'll investigate.

> Xbox, PlayStation, Nintendo
A / ✕ / B - Jump/Confirm
B / 〇 / A - Cancel
X / □ / Y - Shoot
Y / △ / X - Inventory/Skip

I'll take this into consideration, thank you!

> Also could it be possible to add the ability to rebind the menu controls? For example, if one is playing the with a Switch Pro Controller, they could change the Confirm button to A (East) or someone prefers to change it to B (South) on the same controller.

I'll try to do something about this too.

**Comment by jozsefsallai** [comment]
The bug you described was fixed, menu controls are now remappable separately, and I updated the default controls a little*.

*) The default shoot button is now West (X/square/Y) and the default map system button is East (B/circle/A). The other controls remained unchanged (but are still remappable).

**Comment by ViperAcidZX** [comment]
Thank you.

**Comment by ViperAcidZX** [comment]
I just tried to remap my controls with the newest AppVeyor build and now it's crashing the game.

**Comment by jozsefsallai** [comment]
The latest AppVeyor release points to a different branch which is a little bit behind. Try this one: https://ci.appveyor.com/project/alula/doukutsu-rs/builds/44332027

**Comment by ViperAcidZX** [comment]
> The latest AppVeyor release points to a different branch which is a little bit behind. Try this one: https://ci.appveyor.com/project/alula/doukutsu-rs/builds/44332027

This one works. Thank you for the updates.

**Comment by ViperAcidZX** [comment]
Sorry to bump a closed issue but I ran into a few problems when using a Switch Pro Controller. 1) The controller bindings on a Switch Pro Controller, both via wired USB and Bluetooth connection, are mixed up compared to XInput and DualShock 4 controllers, and 2) the game assumes I'm using a Wii Pro Controller with the controller prompts being shown in the rebinding menus and in-game, though I'm going to guess this is yet another "feature" implemented by NiCALiS.
