### ISSUE TITLE
Incorrect DualShock 4 D-pad icons

### ISSUE THREAD

**Issue by ViperAcidZX** [doukutsu-rs/doukutsu-rs#152]
When I used a DualShock 4 controller (I was using a V1 variant in this case), in the Options menu the D-pad icons seems to be reversed for Up, Down, Left, and Right which does not match with the design of the D-pad on the controller itself.

![doukutsu-rs x86_64-2022_08_05_18-13-48](https://user-images.githubusercontent.com/19318128/183218749-e78b10de-5dd9-4056-b2a7-ae2ba6019622.png)

**Comment by alula** [comment]
@jozsefsallai lol how did you mess that up

**Comment by jozsefsallai** [comment]
This is a Nicalis moment. The DualShock icons in their button sheet are messed up like that (the layout is the same for every controller type in the sheet *except* DS, where it looks inverted).

I could add a special check to display the correct icons, but is it really worth it? Even if the button icons are wrong, they still have those little arrows pointing to their orientation.

**Comment by dawndus** [comment]
Can someone check if they're the wrong icon in Isaac?

**Comment by jozsefsallai** [comment]
I refuse to believe Nicalis hardcoded every single button, or added a special check for DS, instead of just fixing the sheet. I genuinely feel like they kind of intended these buttons to look like that, given the arrows.

I would love to be proven wrong though. But it would still be hilarious if it's like that on Isaac too.

**Comment by dawndus** [comment]
That's why I want to see it, I'll try to find a screenshot

**Comment by dawndus** [comment]
Found a screenshot, nicalis moment. 

![image](https://user-images.githubusercontent.com/96957561/183225173-a28081da-ea42-486f-950e-77334da1ac16.png)

**Comment by alula** [comment]
wontfix then or let's add an Yet Another Special Case For Nicalis-introduced Quirks?

**Comment by dawndus** [comment]
wontfix, nicalis displays them broken in other games so this is intentional :)

**Comment by ViperAcidZX** [comment]
Well for those who are OCD about these kinds of things like me, I can say it should be possible to edit ``buttons.png`` with a graphics editor (I used Aesprite as to not mess up the color palette information) to correct this "feature".
