### ISSUE TITLE
Two-player mode is not properly optimized for challenges

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#154]
![shot-2022-08-14_15-53-06](https://user-images.githubusercontent.com/101902085/185520060-e02c4c21-c321-4cd9-aa30-a0f6d5f400c3.jpg)
the player doesn't die of he fall here

**Comment by jozsefsallai** [comment]
P2 is truly one of the Cave Story players of all time. When they said "It's Cave Story time!", it's one of their lines ever.

**Comment by Daedliy** [comment]
everyone asks where is p2 but never how is p2 😔

**Comment by RedCoder09** [comment]
when curly said "it's quoting time" i cried. so emotional
