### ISSUE TITLE
<PRI resets the player pose at the wrong time

### ISSUE THREAD

**Issue by kiatus** [doukutsu-rs/doukutsu-rs#16]
video of the issue: https://imgur.com/a/bese25L
it seems that it resets it before the tsc event starts rather than at the end

**Comment by alula** [comment]
seems like it has been fixed at one point but I don't know really when.
![image](https://user-images.githubusercontent.com/6276139/144710678-0453356c-63ef-4504-91ea-fc0a492a1d51.png)
