### ISSUE TITLE
Silent Crash in Menu if profile contains stage ID that doesn't exist in .tbl/.sect

### ISSUE THREAD

**Issue by Enlight1** [doukutsu-rs/doukutsu-rs#160]
When selecting "Start Game", if a save slot contains references to a map where data can't be pulled from stage.tbl/stage.sect (such as when the stage ID is too high), it immediately closes.

It left me scratching my head for a good while before I remembered that by default d-rs saves are in %appdata% and a stray save file from another copy was causing "Start Game" on the main menu to instantly crash when attempting to load the save select previews.

Proposing that an exception is thrown for failing to load profile data in the save select menu, with details logged in the debugger. Perhaps as a fallback the program can throw up a "save corrupted" or similar error and allow for starting a new game in that slot if the user desires?

**Comment by jozsefsallai** [comment]
Fixed in 2b9a0198cbc4b9d57981f34d447f0ec604d272b4
