### ISSUE TITLE
Damage/Exp number popup inaccuracies

### ISSUE THREAD

**Issue by periwinkle9** [doukutsu-rs/doukutsu-rs#163]
- [x] When taking fatal damage (e.g. from a death spike), the damage amount is not displayed
- [ ] The rising animation of damage numbers can be interrupted by inflicting more damage: (https://clips.twitch.tv/SuperLittleAsparagusVoteNay-z4REadr9A0TqpyID)
- [x] When taking damage and also collecting exp drops, the damage/exp numbers replace each other: (https://clips.twitch.tv/CrispyCrowdedStrawberryRickroll-2k73zE3C00chEECs)
- [ ] Damage numbers display instantly for map bosses (Balfrog, Omega, Monster X, etc). Normally they should not appear until after a period of not taking damage

**Comment by alula** [comment]
github please
