### ISSUE TITLE
debug menu not accessible with F12

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#167]
![Picsart_22-10-08_20-31-28-719](https://user-images.githubusercontent.com/101902085/194724503-eeade8eb-98b5-47c5-9e71-ffe5ab8fa1b3.png)

**Comment by jozsefsallai** [comment]
That's because release builds don't have the debug menu. Build the engine yourself in debug mode or enable the `debug_mode` option it in your settings.json if you want to have a debug menu.
