### ISSUE TITLE
32bit when (solved)

### ISSUE THREAD

**Issue by DarkHybrid** [doukutsu-rs/doukutsu-rs#169]
^^^^^^^^^^^^

**Comment by Krunchy0920** [comment]
There used to be 32-bit builds of D-RS but they were dropped, as they kept breaking for quite some time

**Comment by DarkHybrid** [comment]
is there still a way to get it?

**Comment by Daedliy** [comment]
building it to target 32x systems yourself, however it may be a bit of a bumpy ride

**Comment by alula** [comment]
What kind of hardware are you trying to run it on?

**Comment by DarkHybrid** [comment]
Ok!
