### ISSUE TITLE
Booster particles draw in the incorrect position

### ISSUE THREAD

**Issue by itsautumn3** [doukutsu-rs/doukutsu-rs#173]
Booster particle positions (at least when boosting to the right) don't draw in the correct spot, and instead draw closer to the player than they should.

### Cave Story+ Steam ###
![image](https://user-images.githubusercontent.com/49522306/199853915-81a49016-7093-4170-b794-17ad4976c1a3.png)

### Doukutsu-RS ###
![image](https://user-images.githubusercontent.com/49522306/199853930-36755516-42e1-49fc-845e-7bdb34435436.png)

**Comment by periwinkle9** [comment]
The issue seems to be that on line 467 here, the booster exhaust particle should be spawned at `self.x - 0x400` instead of `self.x + 0x400` when the player is boosting to the right:
https://github.com/doukutsu-rs/doukutsu-rs/blob/0f79474aae2c344ecd27cb9995a5a813e004fa49/src/player/mod.rs#L464-L471

**Comment by dawndus** [comment]
Thanks for the details
