### ISSUE TITLE
bug report NPC absolute RNG

### ISSUE THREAD

**Issue by dananothername** [doukutsu-rs/doukutsu-rs#212]
![shot-2023-06-15_13-07-03](https://github.com/doukutsu-rs/doukutsu-rs/assets/101902085/aa631998-dd45-4548-ac23-18f661a4456f)
as you see that top left pignon won't walk left no matter how much i change the rom 
i even brute forced the frame i enter cemetery in a TAS

**Comment by alula** [comment]
dan don't open an issue about correct base game behavior challenge

Before reporting any issue about d-rs, check it against vanilla please. 

The only RNG use in pignon code is when they start to walk,

**Comment by dananothername** [comment]
i think i get it it has to be absolute 
cuz i didn't face this issue in cs+ TAS
