### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ExGuestCJ** [doukutsu-rs/doukutsu-rs#217]
"The application was unable to start correctly (0xc000007b). Click OK to close the application"

**Comment by alula** [comment]
Could you give more relevant details? 
Your version of Windows? 32/64-bit? System specs?

**Comment by ExGuestCJ** [comment]
nevermind i fixed it

**Comment by changeenter** [comment]
> nevermind i fixed it

hey give details I'm having the same problem

**Comment by ExGuestCJ** [comment]
Thats was a while ago but i remember reinstalling visual c++
