### ISSUE TITLE
Executable crashing (Epic Games version/Windows 11)

### ISSUE THREAD

**Issue by DiamondDogEightyFour** [doukutsu-rs/doukutsu-rs#235]
Yeah, I'm lost! From what I understand I should be able to drop the exe into the game's folder and it should run. The window opens for 1 or 2 seconds and just crashes. WTF am I doing wrong?

**Comment by jozsefsallai** [comment]
Try renaming `opengl32.dll` to something else (or moving it to a different folder) and then opening the game.

**Comment by DiamondDogEightyFour** [comment]
Thank you!!!
