### ISSUE TITLE
Player and Entities jitter and misalign to camera movement

### ISSUE THREAD

**Issue by Daedliy** [doukutsu-rs/doukutsu-rs#24]
The slower the camera moves, the more apparent it becomes
![5Stv2sIRUj](https://user-images.githubusercontent.com/53099651/118372060-f4f66b80-b585-11eb-8d6a-8873f2bb2df2.gif)
Entities also misalign at certain circumstances (harder to replicate)
![L2npLNAXSl](https://user-images.githubusercontent.com/53099651/118372147-764dfe00-b586-11eb-98ab-64c48257a8b9.gif)
![QtUzN6Rtjb](https://user-images.githubusercontent.com/53099651/118372513-5f101000-b588-11eb-8e31-b19a226a6ca3.gif)

**Comment by alula** [comment]
That should be fixed in 80a2fc024cd8abcfe78333f5b72aceb543414a40, are you actually using the latest build?

**Comment by Daedliy** [comment]
Just made sure, yes it's from the latest release, unless that's outdated
https://github.com/doukutsu-rs/doukutsu-rs/releases/tag/0.1.0-android6

**Comment by alula** [comment]
the android preview releases are slightly outdated compared to git releases so i can close it ig
