### ISSUE TITLE
Save file not accessible

### ISSUE THREAD

**Issue by PixiePeace** [doukutsu-rs/doukutsu-rs#246]
The "Profile.dat" file is not stored in the folder with Doukutsu-rs. Is there any way to access the save file?

I am using the freeware version of cave story. I have tried to find the save file on both Linux and MacOS, but have not had any success.

<img width="627" alt="Screenshot 2023-12-05 at 3 39 34 PM" src="https://github.com/doukutsu-rs/doukutsu-rs/assets/88836324/24b6b04d-ab34-472a-b163-8b00278539b0">

<img width="761" alt="Screenshot 2023-12-05 at 3 39 03 PM" src="https://github.com/doukutsu-rs/doukutsu-rs/assets/88836324/6710a48c-140a-4723-8888-7b2001a394a9">

**Comment by PixiePeace** [comment]
Thank you. Where would this file be located on linux (SteamOS)?

**Comment by calciume** [comment]
For me it was in `~/.local/share/doukutsu-rs`
