### ISSUE TITLE
Damage indicator jitters randomly 

### ISSUE THREAD

**Issue by Daedliy** [doukutsu-rs/doukutsu-rs#25]
![yhEveQGgKD](https://user-images.githubusercontent.com/53099651/119170656-f1f1f400-ba39-11eb-9014-d226a32e9130.gif)
So far, Balrog seems to be the only one with this issue, as other NPCs don't 
![ezgif-1-24a6a039e631](https://user-images.githubusercontent.com/53099651/119174038-76df0c80-ba3e-11eb-9c4a-fb2c9a6ea94d.gif)

**Comment by alula** [comment]
fixed already
