### ISSUE TITLE
CS+ assets on Android

### ISSUE THREAD

**Issue by colecrouter** [doukutsu-rs/doukutsu-rs#250]
On Android, I copied my CS+ files from my desktop to my phone, and this was the result:
![Screenshot_20240121-225458](https://github.com/doukutsu-rs/doukutsu-rs/assets/15883173/3e1cc838-37e0-4481-9163-786b0882ff00)

In the README, it mentions using the binary as a drop-in replacement for CS+. Soundtrack works, 99% of the textures work; just some characters don't (mc, Tokoro in intro). I'd figured the same functionality isn't available on Android, but I wanted to double check in case I was messing something up.

Thanks for supporting such an awesome project.

![Screenshot_20240121-230715](https://github.com/doukutsu-rs/doukutsu-rs/assets/15883173/1b733e70-c1ff-4d4f-ae1e-73fef01b39a5)
![Screenshot_20240121-230655](https://github.com/doukutsu-rs/doukutsu-rs/assets/15883173/ca170695-5817-44ea-a8c8-490740995cd5)

**Comment by alula** [comment]
Sounds like you copied your files in a wrong way. Everything should work in the same way across all platforms.

**Comment by colecrouter** [comment]
It's possible. I recopied the assets, moved them into the data folder (`/SteamLibrary/steamapps/common/Cave Story+/data/base/*` -> `/doukutsu-rs game data/data`), but no luck. I ran it on my desktop as a sanity check and it works fine there. Am I missing a step?

**Comment by colecrouter** [comment]
My bad; I'd mistakenly copied `/data/base/*` into `/data` because the structures looked identical, but I needed to copy `/data/*` instead, while keeping the old files there.

Interesting that the game still seems to work almost fine that way.
