### ISSUE TITLE
Android users can't use map

### ISSUE THREAD

**Issue by CalibriLight** [doukutsu-rs/doukutsu-rs#27]
There is no button for the map, if you click map system in inventory it gives you inventory screen without description pad (my english bad, sorry for errors)
![Screenshot_2021-06-07-13-06-28](https://user-images.githubusercontent.com/59058076/120990476-2111a080-c770-11eb-820d-c24b43abb361.jpg)

**Comment by alula** [comment]
It's a general issue - map has not been implemented yet.

**Comment by alula** [comment]
Map system is now implemented
