### ISSUE TITLE
Japanese fonts do not load properly

### ISSUE THREAD

**Issue by GenkaiToppa** [doukutsu-rs/doukutsu-rs#285]
Issue on Arch (possible also other systems but I only tested on Arch host and Arch VM) where Japanese fonts are not loaded properly. Solution was to delete JP fonts in data/. Tested with functional JP locale config (fonts are bundled but I did it to test just in case).

To resolve:

a) add to README a "Troubleshooting" section instructing users to delete JP fonts in data/ if JP font does not correctly load
or
b) Default to using built-in fonts and add a launch flag to use fonts in data/
or
c) Do not change default behavior and add a launch flag to use built-in fonts

Additionally, it would be good for documentation to note that built-in fonts exist and will be used if necessary fonts are not found in data/. I was only able to discover this due to a comment on an unrelated issue.

**Comment by GenkaiToppa** [comment]
Update: tested on Macbook Air M2 (tested with JP locale as well). Same issue. Resolved by deleting existing fonts. 3/3 on this issue so b) looks like the most appealing solution to me.

**Comment by alula** [comment]
Could you clarify which version of the game you're using?

If you're referring to Steam CS+, it's a known issue, which is caused by CS+ using broken/non-compliant BMP headers (Nicalis BMP code assumes a very specific pixel format, it also has other quirks like reading 15bpp images as 16bpp).

Specifically `csfontjp_00.bmp` specifies it's pixel format as RGB and not RGBA, which causes compliant software (like doukutsu-rs and most image editors) to ignore the alpha channel.

The other broken file is one of nemesis challenge spritesheets, which contains 17 color entries in the palette and uses 4bpp format.

**Comment by GenkaiToppa** [comment]
I made my original post in haste. Deleting JP fonts only fixes the titlescreen. After getting the title screen working (white blobs -> legible font) I closed the the game. Not realizing that the issue had not been fully resolved. On both Arch and Mac, the first opening line after starting the game appears as so:

![image](https://github.com/user-attachments/assets/d0f2bd8b-2bf1-435f-9e0a-7257de4ad29b)

This is true across Arch (Epic Games) and MacBook Air M2 (Epic Games & Steam version). 

Cannot test Arch with Steam data files since I already refunded the game on steam.

**Comment by GenkaiToppa** [comment]
Spent a while trying debug the code unsuccessfully (I only touch C & Python and this was literally the first time I've even compiled rust). So I did a sanity check by running under Windows. Still the same issue.

This prompted me to test stable and it worked under all conditions (after deleting JP bmp):

![image](https://github.com/user-attachments/assets/6bce4500-6dd2-489d-a61d-b5a5c04ac474)

Moving forward there's two things that need to happen:

1) Figure out which commit after last stable broke Japanese (and then fix it).

Its still pulling from builtin_font_1.png and builtin_font_2.png but something about the input is messed up.

2) Change README and remove recommendation for users to use Nightly builds. Nightly isn't well tested enough to push to end users b/c a core functionality of the engine was broken on nightly without anyone noticing.

**Comment by alula** [comment]
Probably a regression from #259

**Comment by GenkaiToppa** [comment]
This is my first time trying to contribute to open source. Please let me know if I did not follow proper guidelines/rules.

**Comment by GenkaiToppa** [comment]
Issue has been resolved.
