### ISSUE TITLE
weird line breaks where they shouldn't be

### ISSUE THREAD

**Issue by kiatus** [doukutsu-rs/doukutsu-rs#29]
![26-06-21_20-04-38](https://user-images.githubusercontent.com/46826226/123528932-bd68fc00-d6b9-11eb-9173-292c2e840f47.png)

<MSG<TUR- Polar Star -
The most basic gun.
It bears the mark of Polaris.
<WAI9999<END
maybe it's the way the tsc gets "compiled"?

**Comment by alula** [comment]
fixed
