### ISSUE TITLE
(android) textboxes with facepics are broken

### ISSUE THREAD

**Issue by CalibriLight** [doukutsu-rs/doukutsu-rs#33]
F to textboxes :(

https://user-images.githubusercontent.com/59058076/140684179-88dd5587-a86a-45a6-8f1b-6a3d50675a92.mp4

**Comment by alula** [comment]
Which data files and build are you using? Cannot reproduce it on master.
![image](https://user-images.githubusercontent.com/6276139/140711150-479c9cbd-3f55-45c0-9abf-8ea9178fd689.png)

**Comment by CalibriLight** [comment]
> Which data files and build are you using? Cannot reproduce it on master. ![image](https://user-images.githubusercontent.com/6276139/140711150-479c9cbd-3f55-45c0-9abf-8ea9178fd689.png)

From doukutsu-rs/gamedata
