### ISSUE TITLE
Tile rendering issues

### ISSUE THREAD

**Issue by MeguminSama** [doukutsu-rs/doukutsu-rs#4]
When running the latest build of doukutsu-rs, Tiles seem to jitter at random intervals.

See a demonstration video here: https://imgur.com/a/nWdmg44

Timeline of the video is as follows:

- 20 seconds: You can see the door flickering as I navigate the Start Point map.
- 26 seconds: You can see the tile borders glitching at seemingly random intervals.

**Comment by alula** [comment]
fixed in cf5ee5b9c580f9a157be82edcfcacaeef8dd1b02
