### ISSUE TITLE
On screen Controller Mapping

### ISSUE THREAD

**Issue by Caco-o-sapo** [doukutsu-rs/doukutsu-rs#54]
It's more a request, in my phone the controls are at the middle of the screen, it's not bad but it makes difficult on boss battles since they are in a strange position. It would be great if I could change the positions and stuff. Thanks

**Comment by ViperAcidZX** [comment]
I second this because I want to play this with a controller but nothing registers with my Xbox One controller on the PC version of doukutsu-rs and I'm not sure how to even remap controller buttons if controllers are even supported.

**Comment by Caco-o-sapo** [comment]
> I second this because I want to play this with a controller but nothing registers with my Xbox One controller on the PC version of doukutsu-rs and I'm not sure how to even remap controller buttons if controllers are even supported.

I think that I should have specified that is the Mobile Version that I'm talking

**Comment by jozsefsallai** [comment]
Closing this in favor of #34. Control remapping already works on desktop so it's a matter of enabling it for mobile.
