### ISSUE TITLE
Assorted bugs

### ISSUE THREAD

**Issue by Daedliy** [doukutsu-rs/doukutsu-rs#60]
- [x] Teleporter SFX does not play during cutscenes
- [x] Kazuma's bike does not emit smoke after crashing it
- [x] Labyrinth Balrog boss fight missles emit trails on the wrong end
- [x] King will face the wrong way during the Rabid Toroko cutscene
- [x] Curly still shoots Machine Gun bullets despite holding the Polar Star in the Labyrinth 
- [x] Curly's air bubble does not show up when she turns her back after Core boss fight
- [x] Curly isn't launched to the left after getting blown up in the Core room cutscene
- [x] The Sisters don't close their mouths to getting damaged or defeated
- [x] Orangebell bat sprite is stuck to flying left 
- [x] Gunfish aren't bobbing
- [x] Player 1 vanishes if player 2 drowns
- [x] Ma'Pignon only faces left instead of towards the player when beaten

**Comment by dawndus** [comment]
Fireball issue is related to #37
