### ISSUE TITLE
Download data doesn't works

### ISSUE THREAD

**Issue by Sergei-Alekseev** [doukutsu-rs/doukutsu-rs#64]
See scrnsht
![Screenshot_20220217-101824](https://user-images.githubusercontent.com/28693250/154425446-1ec634fa-8b1b-4dc6-9707-12d3964d6c67.png)

**Comment by jozsefsallai** [comment]
Closing this because it's a stale issue, no one else could reproduce it, and we're updating the data download logic in the next version anyway.
