### ISSUE TITLE
curly brace sprite looks weird in curly story and machine gun challenge (on original graphics)

### ISSUE THREAD

**Issue by arceuss** [doukutsu-rs/doukutsu-rs#65]
see screenshots
on latest commit btw on windows x86_64
![image](https://user-images.githubusercontent.com/28229451/154785050-790b3c8d-7603-4263-b650-344485d7f7a1.png)
![image](https://user-images.githubusercontent.com/28229451/154785053-8b509fd5-c1e4-4158-b945-1958e62b467a.png)
![image](https://user-images.githubusercontent.com/28229451/154785063-5cec4d78-b964-403c-83e5-17c6dfb6fd7b.png)

**Comment by dawndus** [comment]
Fixed in 067bcc5.
