### ISSUE TITLE
Assorted Bugs & Inconsistencies 3

### ISSUE THREAD

**Issue by Daedliy** [doukutsu-rs/doukutsu-rs#67]
- [x] (CS+ Switch) Water ripples are disabled when "Lighting effects" is Off
- [x] (D-RS) Some menus and occasionally the cursor snap into place on startup or when loading a new menu
- [x] (D-RS) When text is being selected in the debug console, D-RS will stop responding until selection is cleared
- [x] (CS+ Switch) Sand caret doesn't emit when walking on sand tiles 
- [x] (CS+) Retrying any challenge starts in a incorrect spot and overrides weapons with the challenge Machinegun (again?)
- [x] (D-RS) Challenge times overwriting 290.rec
- [x] (CS+ Switch) Water is missing it's refraction
- [x] (CS+ Switch) Water ripples are too noisy
- [x] (CS+ Switch) Npcs don't splash when jumping in water
- [x] (D-RS) Stray flickering pixels on the very rightmost side of the Cutscene Skip box
- [x] (D-RS) Fade Transition breaks if window size is changed **at all** on any Data
- [x] (CS+) Incorrect difficulty costume with the player's cutscene NPC and Pause Menu cursor #69 
- [x] (D-RS) Skip Cutscene box can briefly show up if you try to skip the Fade Transition 
- [x] (CS+ Switch) Jukebox entries bleed a pixel on the bottom if the window is resized any larger
- [x] (D-RS) Challenges aren't ordered by `mod.txt`
- [x] (D-RS) Challenge locking / unlocking
- [x] (D-RS) Find and display Nicalis logo / Custom logo splash on start
- [x] (Freeware) Fix Balrog float after Mimiga Village shack cutscene  
- [x] (CS+) Broken TSC on Assembly Hall door #74 
- [x] (D-RS) Last phase Ballos bleeds upwards
- [x] (D-RS) Sisters boss fight has multiple inconsistencies 
- [x] (D-RS) The Mini Cores that orbit around Undead Core dont animate properly
- [x] (D-RS) Toggling **Original Textures** causes specific NPCs to turn into white squares until the player leaves the level and WILL cause TSC to give up and softlock on some cutscenes
<details>
  <summary>Footage </summary>

https://user-images.githubusercontent.com/53099651/155991283-d58c3e40-cd01-4299-87b1-efaebf2684a6.mp4

![image](https://user-images.githubusercontent.com/53099651/155991667-1ff6f2d5-2b53-4bf4-8aa3-6b93a08ac059.png)

</details>

**Comment by dawndus** [comment]
🎉
