### ISSUE TITLE
some bugs in windows d-rs

### ISSUE THREAD

**Issue by dancrime** [doukutsu-rs/doukutsu-rs#88]
doukutsu-rs.x86_64 with gog data folder
challenges are missed up
#they are named easyMod/mod/...etc
#curly story but qoute is showed insted
#time trial some aria art is missing in the first map only
#boss mod same map issue and qoute start near monster x
#kaze/mod also map art missing
# Nemesis here when qoute take booster 2.0 it works along side with 0.8 the tow work at same time  (must open menu and acuire it manly to fix it) here is the link https://youtu.be/hktqHKEJcOM
-fazz core doent wait for qoute invencebilty (it hit him towice in row)
- nemesis doesnt directly levelup when taking one xp 
- the second ghost cat is insaid the top up blocks 

and with switch data qoute start challenges a little bit to the left

**Comment by dawndus** [comment]
Many of these have already been fixed, please stop submitting bug reports with old builds.

**Comment by jozsefsallai** [comment]
Told you many many times to 

TEST

ON

PC

WITH

THE

LATEST

BUILD.

What you're describing is neither the latest build, nor PC. You are still sending bug reports while using very old builds on Android. Stop doing that please and also stop writing misleading titles for your issues in order to get the maintainers' attention (you lied about this being on Windows when it's VERY CLEARLY Android).

**Comment by dancrime** [comment]
https://github.com/doukutsu-rs/doukutsu-rs/releases
this what i see

**Comment by jozsefsallai** [comment]
Yeah those are STABLE builds.

You need the NIGHTLY builds from AppVeyor: https://ci.appveyor.com/project/alula/doukutsu-rs

**Comment by dancrime** [comment]
nightly builds surly has some fixes but not what i said early

**Comment by jozsefsallai** [comment]
> nightly builds surly has some fixes but not what i said early

What is still broken then?

**Comment by dancrime** [comment]
everything i said in this bug report about nimess challenge
