### ISSUE TITLE
Ammo count does not appear for player 2 (on pc)

### ISSUE THREAD

**Issue by Awesomegamer6566** [doukutsu-rs/doukutsu-rs#91]
![bug](https://user-images.githubusercontent.com/50709579/158456738-008ca9e1-919a-4626-a831-859db3799e2e.gif)
Just noticed this while playing with a friend. Not sure if this happens on the Switch version.

**Comment by dawndus** [comment]
![doukutsu-rs_QgSTxpOwow](https://user-images.githubusercontent.com/96957561/158723419-4b16824e-118f-4df4-99e6-d2a04b49aa8c.gif)

Can't reproduce, if someone else can feel free to comment and reopen the issue.
