### ISSUE TITLE
Some sprites don't appear in challenges 

### ISSUE THREAD

**Issue by Awesomegamer6566** [doukutsu-rs/doukutsu-rs#93]
![image](https://user-images.githubusercontent.com/50709579/159302091-64dccd5a-7f6d-4b87-aa02-17f7fc382a96.png)
![bug](https://user-images.githubusercontent.com/50709579/159302124-4f355224-015e-45f1-8f93-c33f796fa35d.gif)
This only effects enemies that are new to CS+ (like the Curly clones). I think this bug also disables how the enemies work. Probably only happens on PC.

**Comment by jozsefsallai** [comment]
Known issue, we are just working on implementing the Wind Fortress NPCs.

**Comment by dawndus** [comment]
Closing this since it's known and being worked on.
