### ISSUE TITLE
Support for mods?

### ISSUE THREAD

**Issue by ViperAcidZX** [doukutsu-rs/doukutsu-rs#96]
Are those in the cards too? Because I would love to play Cave Story+ with doukutsu-rs the AGTP mod from the Plus Porter package  along the benefits this port has to offer.

**Comment by alula** [comment]
Mods are already supported, just apply necessary patches to the data folder in the same way you do with CS+.

**Comment by ViperAcidZX** [comment]
Sorry to necro a closed question, but I am having problems with the latest dev build of doukutsu-rs and the [Aeon Genesis TL port](https://gbatemp.net/threads/aeon-genesis-cave-story-port-nintendo-switch.575809/) for Cave Story+ Remastered. Whenever I try to enter the room with Balrog in Grasstown with the demolition robot, the game just crashes.
